# GCP Workload Identity - Secure, keyless authentication
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dell-boca-api
  annotations:
    iam.gke.io/gcp-service-account: api@PROJECT_ID.iam.gserviceaccount.com

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dell-boca-n8n
  annotations:
    iam.gke.io/gcp-service-account: n8n@PROJECT_ID.iam.gserviceaccount.com

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dell-boca-webui
  annotations:
    iam.gke.io/gcp-service-account: webui@PROJECT_ID.iam.gserviceaccount.com
