apiVersion: v1
kind: Namespace
metadata:
  name: dell-boca-boys-v2
  labels:
    name: dell-boca-boys-v2
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
